version: "3"
services:
  api01: &api
    build:
      context: .
      args:
        - NODE_NAME=diogenes
    container_name: api01
    hostname: api01
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_NAME=diogenes
      - NODE_TYPE=master
      - BOOTSTRAP_NODE=alexander@api02
      - ERL_MAX_PORTS=2048
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '250MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    ports:
      - "8081:8080"
    environment:
      - NODE_NAME=alexander
      - BOOTSTRAP_NODE=diogenes@api01
      - ERL_MAX_PORTS=2048

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50MB'
